### ISSUE TITLE
Documentation for a locally deployed data space

### ISSUE THREAD

**Issue by sermars** [FIWARE-Ops/fiware-gitops#44]
Hi,
We are trying to deploy an entirely local data space with the minimum services to use this (operator, marketplace and a couple of connectors). The goal is that it is easy to deploy, using some kind of Terraform tool and that it is autonomous; third-party services such as ishare or gaiax are not needed, even if this means having our certificates and not being able to verify the real identity of the user who claims to be. However, being something for testing, it is unimportant in this case.

This [repo](https://github.com/FIWARE-Ops/fiware-gitops/tree/master/aws/dsba) is very focused on cloud deployment. Still, the cost is unaffordable for testing, and it would be more comfortable to have something local or any other type of Kubernetes cluster. To make this adaptation, some clarifications or guides on how to configure the services would be good. Maybe some are already described in another repo, but I don’t know.

- It would be interesting to have a guide of the essential variables that need to be modified to correctly deploy everything and some description that facilitates understanding why one value or another.

-  Regarding Ingress, which services really need this configuration? I suppose not all of them need to be exposed outside the cluster. Is there an example of deployment using ingress?

- About the dids:
  - How would you configure the services with did:key?
  - Using did:web, do you need to create a web server, that does not appear in the diagram, to store the certificates?
  - Does any service have the ssikit API to generate the dids?

- About specific services of the ds-operator:
  - **kong** has a dblessConfig configuration that refers to the configmap: kong-one-configmap, is this published somewhere?
  - **PDP**, the ishare parameter. What is it, and how should it be configured?
  - **trusted-participants-registry**, there are a series of certificates under the satellite parameter that I would like to know what they are and if they are necessary for the deployment we intend to do.
  - The **trusted-issuers-list** has two ingress addresses. Are these addresses part of this same service? Why is this?

**Comment by wistefan** [comment]
Hi, thanks for the summary. However, are you aware of the data-space-connector repo - https://github.com/FIWARE/data-space-connector 
Would it be ok for you to move it there? The topics are much more fitting in this.
Best,
Stefan

**Comment by sermars** [comment]
Yes, of course, you can move it wherever you think is best. I put it here because it’s not just the connector that I want to implement, but an entire data space environment.

Can I move it directly or do you mean to close this and copy it to the other repository?

**Comment by wistefan** [comment]
You would have to close and copy. The other one is a better match, since this repo is for everything in our cluster, not just dataspaces.
